name: Testing aiocache-dynamodb

on:
  pull_request:
      branches:
          - main
          - develop
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install the project
        run: make sync
      - name: Run typing/linting check
        run: make check
  pytest:
    strategy:
      matrix:
        py_version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: "ubuntu-latest"
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.py_version }}
      - name: Install the project
        run: make sync
      - name: Run pytest check for Python ${{ matrix.py_version }}
        run: make test
      - name: Show Coverage
        if: github.event_name == 'pull_request' && matrix.py_version == '3.12'
        uses: orgoro/coverage@v3.2
        with:
            coverageFile: coverage.xml
            thresholdAll: 0.90
            thresholdNew: 0.95
            token: ${{ secrets.GITHUB_TOKEN }}
